name: Build and Publish Release

on:
  workflow_dispatch:

concurrency:
  group: build-opencost
  cancel-in-progress: true

jobs:
  build-and-publish-opencost:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: 'opencost/opencost'
          ref: 'develop'
          path: ./opencost  

      - name: Set SHA
        id: sha
        run: |
          pushd ./opencost
          echo "OC_SHORTHASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          popd

      - name: Set OpenCost Image Tags
        id: tags
        run: |
          echo "IMAGE_TAG=ghcr.io/opencost/opencost:${{ steps.sha.outputs.OC_SHORTHASH }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=ghcr.io/opencost/opencost:latest" >> $GITHUB_ENV
          echo "IMAGE_TAG_UI=ghcr.io/opencost/opencost-ui:${{ steps.sha.outputs.OC_SHORTHASH }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_UI_LATEST=ghcr.io/opencost/opencost-ui:latest" >> $GITHUB_ENV
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up just
        uses: extractions/setup-just@v1
      
      - name: Build and push (multiarch) OpenCost
        working-directory: ./opencost
        run: |
          just build '${steps.tags.outputs.IMAGE_TAG}'
          just build '${steps.tags.outputs.IMAGE_TAG_LATEST}'

      - name: Build and push (multiarch) OpenCost UI
        working-directory: ./opencost/ui
        run: |
          just build '${steps.tags.outputs.IMAGE_TAG_UI}'
          just build '${steps.tags.outputs.IMAGE_TAG_UI_LATEST}'